[package]
name = "exchange"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
domain.workspace = true

rust_decimal.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
reqwest.workspace = true
hmac.workspace = true
sha2.workspace = true
hex.workspace = true
tokio.workspace = true
futures-util.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
rust_decimal_macros = "1"
