[package]
name = "engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
domain.workspace = true
data.workspace = true
sim.workspace = true
store.workspace = true
strategies.workspace = true

rust_decimal.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
rust_decimal_macros = "1"
tempfile = "3"
